# Generated by Django 5.1.4 on 2025-01-22 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name="Nom d'utilisateur")),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Photo de profil')),
                ('numero_telephone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit être au format international. Exemple : +123456789', regex='^\\+?1?\\d{9,15}$')], verbose_name='Numéro de téléphone')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville de résidence')),
                ('adresse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse postale')),
                ('emploi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession')),
                ('employeur', models.CharField(blank=True, max_length=100, null=True, verbose_name='Employeur')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Compte vérifié')),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Code de vérification')),
                ('verification_code_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expiration du code de vérification')),
                ('iban', models.CharField(blank=True, max_length=34, null=True, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=11, null=True, verbose_name='BIC')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('is_staff', models.BooleanField(default=False, verbose_name="Accès à l'admin")),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superutilisateur')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
    ]
